apiVersion: v1
kind: service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
  spec:
    type: NodePort
    ports:
      port: 80
      nodePort: 30080
    selector:
      name: nginx

